 services:
  joyfy-api:
    container_name: joyfy-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/joyfy
    working_dir: /usr/src/joyfy

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  joyfy-batch:
    container_name: joyfy-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/joyfy
    working_dir: /usr/src/joyfy

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
